# Generated by Django 4.2.25 on 2025-10-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='max_overbook_day',
            field=models.PositiveIntegerField(default=0, help_text='Máximo de sobrecupos permitidos por día para este dentista'),
        ),
        migrations.AddField(
            model_name='slotagenda',
            name='max_overbook',
            field=models.PositiveIntegerField(default=0, help_text='Cuántos sobrecupos adicionales se permiten en este slot'),
        ),
    ]
