# Generated by Django 4.2.25 on 2025-10-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='servicios',
            field=models.ManyToManyField(blank=True, help_text='Servicios que puede realizar este dentista', related_name='dentistas', to='agenda.servicio'),
        ),
    ]
