# Generated by Django 4.2.25 on 2025-10-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_dentista_max_overbook_day_slotagenda_max_overbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dentista',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='slotagenda',
            options={'ordering': ('fecha', 'hora')},
        ),
        migrations.AlterField(
            model_name='dentista',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
