# Generated by Django 4.2.25 on 2025-10-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_dentista_options_alter_paciente_options_and_more'),
    ]

    operations = [
    ]
