# Generated by Django 4.2.25 on 2025-10-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_region_dentista_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='rut',
            field=models.CharField(blank=True, help_text='RUT del paciente (ej: 12.345.678-9)', 
                                   max_length=15, null=True, unique=False),
        ),
    ]
