# Generated by Django 5.2.7 on 2025-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_region_dentista_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='rut',
            field=models.CharField(default='SIN_RUT_TEMP', max_length=12),
            preserve_default=False,
        ),
    ]
