# Generated by Django 4.2.25 on 2025-10-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_paciente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(help_text='RUT del paciente (ej: 12.345.678-9)', max_length=15, unique=False),
        ),
    ]
